name: emotion_map_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # State
  hooks_riverpod: ^3.1.0
  flutter_hooks: ^0.21.3+1
  riverpod_annotation: ^4.0.0

  # API
  retrofit: ^4.9.2
  dio: ^5.9.0

  # Model
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Route
  auto_route: ^11.1.0

  # Widget
  loader_overlay: ^5.0.0
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.2
  
  # Storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  
  # Social Login
  flutter_naver_login: ^2.1.1
  kakao_flutter_sdk_user: ^1.10.0
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1

  # Util
  flutter_dotenv: ^5.2.1
  collection: ^1.19.1

  # Native Util
  url_launcher: ^6.3.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # State
  riverpod_generator: ^4.0.0+1

  # API
  retrofit_generator: ^10.2.1

  # Model
  freezed: ^3.2.3
  json_serializable: ^6.11.1

  # Runner
  build_runner: ^2.10.4

  # Route
  auto_route_generator: ^10.4.0

  # Lint
  flutter_lints: ^6.0.0
  custom_lint: ^0.8.1
  riverpod_lint: ^3.1.0

  # CLI
  spider: ^4.2.3
  change_app_package_name: ^1.4.0
  openapi_generator_cli: ^6.1.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - .env.dev
    - assets/webp/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/font/NotoSansKR-Thin.ttf
          weight: 100
        - asset: assets/font/NotoSansKR-ExtraLight.ttf
          weight: 200
        - asset: assets/font/NotoSansKR-Light.ttf
          weight: 300
        - asset: assets/font/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/font/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/font/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: assets/font/NotoSansKR-Bold.ttf
          weight: 700
        - asset: assets/font/NotoSansKR-ExtraBold.ttf
          weight: 800
        - asset: assets/font/NotoSansKR-Black.ttf
          weight: 900