# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_require 'dotenv'

before_all do
  Dotenv.overload '../../.env.script'
end

default_platform(:ios)

platform :ios do
  def get_version_info
    yaml_file_path = "../../pubspec.yaml"
    data = YAML.load_file(yaml_file_path)
    version_and_no = data["version"].split("+")
    {
      version: version_and_no[0],
      build_number: version_and_no[1]
    }
  end

  desc "Deploy Firebase Dev"
  lane :deploy_firebase_dev do
    Dir.chdir "../.." do
      sh("fvm", "flutter", "build", "ipa", "--release", "--flavor", "dev", "--export-options-plist=ios/Runner/Dev/ExportOptions.plist")
    end

    firebase_app_distribution(
      app: ENV["IOS_APP_DEV"],
      service_credentials_file: "../service-account.json",
      debug: false,
      groups_file: "fastlane/testers-groups.txt",
      release_notes_file: "../release-notes-dev.txt",
      ipa_path: "../build/ios/ipa/emotion_map_app.ipa",
    )
  end
end