# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_require 'dotenv'

before_all do
  Dotenv.overload '../../.env.script'
end

default_platform(:android)

platform :android do
  def get_version_info
    yaml_file_path = "../../pubspec.yaml"
    data = YAML.load_file(yaml_file_path)
    version_and_no = data["version"].split("+")
    {
      version: version_and_no[0],
      build_number: version_and_no[1]
    }
  end
  
  desc "Deploy Firebase Dev"
  lane :deploy_firebase_dev do
    version_info = get_version_info
    version = version_info[:version]
    no = version_info[:build_number]

    Dir.chdir "../.." do
      sh("fvm", "flutter", "build", "apk", "--release", "--flavor", "dev", "--build-number", no, "--build-name", version)
    end

    firebase_app_distribution(
      app: ENV["ANDROID_APP_DEV"],
      service_credentials_file: "../service-account.json",
      debug: false,
      groups_file: "fastlane/testers-groups.txt",
      release_notes_file: "../release-notes-dev.txt",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-dev-release.apk",
    )
  end
end